window.opacity = 0.95
working_directory = "None"
# Colors (Gruvbox light)

import = [
  # uncomment the flavour you want below:
  "~/.config/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

## Default colors
#[colors.primary]
## hard contrast background = = '#f9f5d7'
#background = '#fbf1c7'
## soft contrast background = = '#f2e5bc'
#foreground = '#3c3836'
#
# Normal colors
#[colors.normal]
#black   = '#fbf1c7'
#red     = '#cc241d'
#green   = '#98971a'
#yellow  = '#d79921'
#blue    = '#458588'
#magenta = '#b16286'
#cyan    = '#689d6a'
#white   = '#7c6f64'
#
## Bright colors
#[colors.bright]
#black   = '#928374'
#red     = '#9d0006'
#green   = '#79740e'
#yellow  = '#b57614'
#blue    = '#076678'
#magenta = '#8f3f71'
#cyan    = '#427b58'
#white   = '#3c3836'

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "Iosevka Nerd Font Mono"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window.dimensions]
columns = 140
lines = 38

[window.padding]
x = 10
y = 10
